export const searchCopyByLanguage = {
  es: {
    eyebrow: 'Buscar',
    heading: 'Encuentra noticias rápido',
    intro: 'Busca en los títulos y resúmenes de nuestra cobertura.',
    placeholder: 'Buscar noticias...',
    submit: 'Buscar',
    emptyPrompt: 'Escribe para buscar noticias.',
    emptyState: 'Aún no has escrito una búsqueda.',
    noResults: 'No hay resultados para',
    tryAnother: 'Prueba con otra palabra clave.',
    resultSingular: 'resultado',
    resultPlural: 'resultados',
    forQuery: 'para',
    page: 'Página',
    of: 'de',
    previous: 'Anterior',
    next: 'Siguiente',
    searching: 'Buscando...',
    unavailable: 'La búsqueda no está disponible temporalmente.',
    loadFailure: 'No pudimos cargar el índice de búsqueda en este momento.',
  },
  en: {
    eyebrow: 'Search',
    heading: 'Find news quickly',
    intro: 'Search the headlines and summaries in our coverage.',
    placeholder: 'Search news...',
    submit: 'Search',
    emptyPrompt: 'Type to search the news.',
    emptyState: 'You have not entered a search yet.',
    noResults: 'No results for',
    tryAnother: 'Try another keyword.',
    resultSingular: 'result',
    resultPlural: 'results',
    forQuery: 'for',
    page: 'Page',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    searching: 'Searching...',
    unavailable: 'Search is temporarily unavailable.',
    loadFailure: 'We could not load the search index right now.',
  },
  it: {
    eyebrow: 'Cerca',
    heading: 'Trova rapidamente le notizie',
    intro: 'Cerca nei titoli e nei sommari della nostra copertura.',
    placeholder: 'Cerca notizie...',
    submit: 'Cerca',
    emptyPrompt: 'Scrivi per cercare le notizie.',
    emptyState: 'Non hai ancora inserito una ricerca.',
    noResults: 'Nessun risultato per',
    tryAnother: "Prova un'altra parola chiave.",
    resultSingular: 'risultato',
    resultPlural: 'risultati',
    forQuery: 'per',
    page: 'Pagina',
    of: 'di',
    previous: 'Precedente',
    next: 'Successivo',
    searching: 'Ricerca in corso...',
    unavailable: 'La ricerca non è temporaneamente disponibile.',
    loadFailure: 'Non è stato possibile caricare ora l’indice di ricerca.',
  },
} as const;
